# Generated by Django 5.2.7 on 2025-10-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
