# Generated by Django 5.2.7 on 2025-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_orderitem_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
