# Generated by Django 5.2.7 on 2025-11-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied')], default='none', max_length=20),
        ),
    ]
