# Generated by Django 5.2.7 on 2025-11-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_orderitem_refund_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
