# Generated by Django 5.2.7 on 2025-12-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customuser_banned'),
        ('main', '0010_review'),
    ]

    operations = [
    ]
