# Generated by Django 5.2.7 on 2025-12-02 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_0006_alter_customuser_banned_0010_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('user_created', 'User created'), ('product_created', 'Product created'), ('admin_action', 'Admin action')], max_length=32)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='banned',
            field=models.BooleanField(default=True),
        ),
    ]
