@startuml US-09: Payment & Billing
actor User
participant System

User -> System: Click "Continue to Payment"
System -> User: Display Payment & Billing Form

loop Until Payment Info is Valid
    User -> System: Enter Payment & Billing Info
    System -> System: Verify Payment Info
    System -> User: Prompt to re-enter details if invalid
end

System -> System: Bill User
System -> User: Display "Success" and Receipt
@enduml
