@startuml US-05 Display Cart Popup - Activity
start
:Click Cart Icon;
:Open Cart Popup;

if () then (Clicked Checkout Button)
  :Proceed to Checkout;
  :Complete Checkout;
  stop
else (Not Clicked Checkout)
  if () then (Click outside Popup)
    :Close Popup;
    stop
  endif
  stop
endif
@enduml