@startuml US-06 Activity
start
:User clicks "Add to Cart" button;
:Item is added to cart list;
if () then (Potential To Open Cart Popup)
  :Display Cart Popup;
else (No Popup)
  :Stay on Product Page;
endif
' Issue #77 has a relevant comment
stop
@enduml