@startuml US-01 - User Account Creation
[*] --> StartForm

StartForm --> PersonalDetailEntry : Click "Start Account Creation"
PersonalDetailEntry : Do: enterPersonalDetails

PersonalDetailEntry --> CreatePassword : Scroll Down to "Create Password"
CreatePassword : Do: enterPassword

CreatePassword --> PasswordCheck : Submit Password
PasswordCheck : Do: validatePasswords
PasswordCheck --> CreatePassword : Passwords Do Not Match
PasswordCheck --> CreateAccount : Passwords Match
CreateAccount : Do: createAccount


CreateAccount --> [*]



/'PersonalDetailEntry --> EnterPassword : Enter Password

PersonalDetailEntry --> PasswordCheck : Submit Passwords
PasswordCheck : Do: validatePasswords
PasswordCheck --> PersonalDetailEntry : Passwords Do Not Match
PasswordCheck --> DetailsForm : Passwords Match

DetailsForm : Do: enterDetails
DetailsForm --> Validating : Submit Details
Validating : Do: validateDetails
Validating --> DetailsForm : Invalid Details
Validating --> Success : Valid Details

Success : Do: createAccount
Success --> [*]'/
@enduml
