@startuml US-01 - Account Creation Activity

start
:Click "Create Account" on ribbon anywhere;
repeat
    :Display Account Creation Form;
    :Enter Account Details;
repeat while () is (Error with Input) not (All Details Valid)
:Submit Account Details;
:Display "Success" and Create Account;
:Send verification email;
if () then (User clicks verification link)
    :Verify email and activate account;
else (User does not verify email)
    :Account can be used but no recovery options;
endif
stop
@enduml