

@startuml US-01 - User Account Creation
left to right direction
actor User
actor DB

rectangle System {
  usecase "Continue to Start Account Creation" as U1
  usecase "Enter Personal Details" as U2
  usecase "Enter username" as U3
  usecase "Enter Password" as U4

}

rectangle DB {
'   usecase "Verify Payment Info" as U3
'   usecase "Prompt for Correct Info" as U4
'   usecase "Bill User" as U5
'   usecase "Display Success & Receipt" as U6
}

User --> U1
User --> U2
User --> U3
User --> U4 
System --> DB

' DB --> U3
' DB --> U4
' DB --> U5
' DB --> U6
@enduml